services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
  web01:
    build: 
      context: ./web01
      dockerfile: Dockerfile
    container_name: web01
  web02:
    build: 
      context: ./web02
      dockerfile: Dockerfile
    container_name: web02
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web01
      - web02
      - dns
